/********************************************************************
* DarkSector_SignalMCCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DarkSector_SignalMCCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDarkSector_SignalMCCint();
extern void G__cpp_setup_inheritanceDarkSector_SignalMCCint();
extern void G__cpp_setup_typetableDarkSector_SignalMCCint();
extern void G__cpp_setup_memvarDarkSector_SignalMCCint();
extern void G__cpp_setup_globalDarkSector_SignalMCCint();
extern void G__cpp_setup_memfuncDarkSector_SignalMCCint();
extern void G__cpp_setup_funcDarkSector_SignalMCCint();
extern void G__set_cpp_environmentDarkSector_SignalMCCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Decay.h"
#include "LeptophobicMC.h"
#include "Meson.h"
#include "ProductionCheck.h"
#include "VB.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DarkSector_SignalMCCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_Decay;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_LeptophobicMC;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_Meson;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_ProductionCheck;
extern G__linked_taginfo G__DarkSector_SignalMCCintLN_VB;

/* STUB derived class for protected member access */
