####################################################
# GEANT4 GDML
#
# File:      vis.mac
#
#
# Date:      11/9/2012
####################################################

/control/verbose 1
/run/verbose 1
/vis/verbose 0

#/vis/open OGL 1000x1000-0+0

#/vis/drawVolume room_physical

#/vis/viewer/set/background black ! !
#/vis/viewer/set/defaultColour white ! ! .3
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenEdge

#/vis/scene/add/axes      0 0 0 5 m

#/vis/viewer/set/viewpointThetaPhi 40 40

#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate

/CRY/input returnElectrons 1
/CRY/input returnNeutrons 1
/CRY/input returnProtons 1
/CRY/input returnGammas 1
/CRY/input returnPions 1
/CRY/input returnKaons 1
/CRY/input returnMuons 1
/CRY/input date 8-25-2013
/CRY/input latitude 41.8
/CRY/input altitude 0
/CRY/input subboxLength 75
#/CRY/input sampleTime

/CRY/update

/run/beamOn 1000000

